In [1]:
import pandas as pd
import requests
import json

In [ ]:
#pip install python-dotenv

In [2]:
import os 
from dotenv import load_dotenv
load_dotenv()

True

In [3]:
token = os.getenv("token")

In [4]:
print(token)

2e1b6aa4e6f43e28f2ee12c898c064df825476d0

In [5]:
response_all= requests.get("https://api.census.gov/data/2019/pep/population?get=NAME,POP&for=state:*&key=2e1b6aa4e6f43e28f2ee12c898c064df825476d0")

In [6]:
response_all.status_code

200

In [7]:
datos_all=response_all.json()
datos_all

[['NAME', 'POP', 'state'],
 ['Alabama', '4903185', '01'],
 ['Alaska', '731545', '02'],
 ['Arizona', '7278717', '04'],
 ['Arkansas', '3017804', '05'],
 ['California', '39512223', '06'],
 ['Colorado', '5758736', '08'],
 ['Delaware', '973764', '10'],
 ['District of Columbia', '705749', '11'],
 ['Connecticut', '3565287', '09'],
 ['Florida', '21477737', '12'],
 ['Georgia', '10617423', '13'],
 ['Idaho', '1787065', '16'],
 ['Hawaii', '1415872', '15'],
 ['Illinois', '12671821', '17'],
 ['Indiana', '6732219', '18'],
 ['Iowa', '3155070', '19'],
 ['Kansas', '2913314', '20'],
 ['Kentucky', '4467673', '21'],
 ['Louisiana', '4648794', '22'],
 ['Maine', '1344212', '23'],
 ['Maryland', '6045680', '24'],
 ['Massachusetts', '6892503', '25'],
 ['Michigan', '9986857', '26'],
 ['Minnesota', '5639632', '27'],
 ['Mississippi', '2976149', '28'],
 ['Missouri', '6137428', '29'],
 ['Montana', '1068778', '30'],
 ['Nebraska', '1934408', '31'],
 ['Nevada', '3080156', '32'],
 ['New Hampshire', '1359711', '33'],
 ['New Jersey', '8882190', '34'],
 ['New Mexico', '2096829', '35'],
 ['New York', '19453561', '36'],
 ['North Carolina', '10488084', '37'],
 ['North Dakota', '762062', '38'],
 ['Ohio', '11689100', '39'],
 ['Oklahoma', '3956971', '40'],
 ['Oregon', '4217737', '41'],
 ['Pennsylvania', '12801989', '42'],
 ['Rhode Island', '1059361', '44'],
 ['South Carolina', '5148714', '45'],
 ['South Dakota', '884659', '46'],
 ['Tennessee', '6829174', '47'],
 ['Texas', '28995881', '48'],
 ['Vermont', '623989', '50'],
 ['Utah', '3205958', '49'],
 ['Virginia', '8535519', '51'],
 ['Washington', '7614893', '53'],
 ['West Virginia', '1792147', '54'],
 ['Wisconsin', '5822434', '55'],
 ['Wyoming', '578759', '56'],
 ['Puerto Rico', '3193694', '72']]

In [13]:
df_all=pd.DataFrame(datos_all)
df_all

                       0         1      2
0                   NAME       POP  state
1                Alabama   4903185     01
2                 Alaska    731545     02
3                Arizona   7278717     04
4               Arkansas   3017804     05
5             California  39512223     06
6               Colorado   5758736     08
7               Delaware    973764     10
8   District of Columbia    705749     11
9            Connecticut   3565287     09
10               Florida  21477737     12
11               Georgia  10617423     13
12                 Idaho   1787065     16
13                Hawaii   1415872     15
14              Illinois  12671821     17
15               Indiana   6732219     18
16                  Iowa   3155070     19
17                Kansas   2913314     20
18              Kentucky   4467673     21
19             Louisiana   4648794     22
20                 Maine   1344212     23
21              Maryland   6045680     24
22         Massachusetts   6892503     25
23              Michigan   9986857     26
24             Minnesota   5639632     27
25           Mississippi   2976149     28
26              Missouri   6137428     29
27               Montana   1068778     30
28              Nebraska   1934408     31
29                Nevada   3080156     32
30         New Hampshire   1359711     33
31            New Jersey   8882190     34
32            New Mexico   2096829     35
33              New York  19453561     36
34        North Carolina  10488084     37
35          North Dakota    762062     38
36                  Ohio  11689100     39
37              Oklahoma   3956971     40
38                Oregon   4217737     41
39          Pennsylvania  12801989     42
40          Rhode Island   1059361     44
41        South Carolina   5148714     45
42          South Dakota    884659     46
43             Tennessee   6829174     47
44                 Texas  28995881     48
45               Vermont    623989     50
46                  Utah   3205958     49
47              Virginia   8535519     51
48            Washington   7614893     53
49         West Virginia   1792147     54
50             Wisconsin   5822434     55
51               Wyoming    578759     56
52           Puerto Rico   3193694     72

In [14]:
df_all.columns = df_all.iloc[0]

In [15]:
df_all.columns

Index(['NAME', 'POP', 'state'], dtype='object', name=0)

In [16]:
res=requests.get("https://api.census.gov/data/timeseries/idb/1year?get=NAME,NAME_2,DATE_CODE,AREA_CODE&for=STATE:*&time=from+1950-01-01+to+1959-12-31&key=2e1b6aa4e6f43e28f2ee12c898c064df825476d0")

In [17]:
res.status_code

500

In [ ]:
datos_year=res.json()
datos_year

In [ ]:
df_year=pd.DataFrame(res)
df_year

In [ ]:
usr_key = f"&key={USCensusAPI.api_key}"

In [18]:
prueba = requests.get("https://api.census.gov/data/1990/pep/int_natcivpop?get=YEAR,TOT_POP,AGE&key=2e1b6aa4e6f43e28f2ee12c898c064df825476d0")

In [19]:
prueba.status_code

200

In [20]:
datos_prueba=prueba.json()
datos_prueba

[['YEAR', 'TOT_POP', 'AGE'],
 ['1990', '247150736', '999'],
 ['1990', '3947313', '0'],
 ['1990', '3769554', '1'],
 ['1990', '3702679', '2'],
 ['1990', '3641649', '3'],
 ['1990', '3703886', '4'],
 ['1990', '3635463', '5'],
 ['1990', '3580577', '6'],
 ['1990', '3647972', '7'],
 ['1990', '3473320', '8'],
 ['1990', '3704888', '9'],
 ['1990', '3641128', '10'],
 ['1990', '3438903', '11'],
 ['1990', '3393344', '12'],
 ['1990', '3323778', '13'],
 ['1990', '3270109', '14'],
 ['1990', '3322354', '15'],
 ['1990', '3284318', '16'],
 ['1990', '3466649', '17'],
 ['1990', '3615588', '18'],
 ['1990', '4046794', '19'],
 ['1990', '3880608', '20'],
 ['1990', '3706504', '21'],
 ['1990', '3562771', '22'],
 ['1990', '3634095', '23'],
 ['1990', '3829705', '24'],
 ['1990', '4023509', '25'],
 ['1990', '4124882', '26'],
 ['1990', '4208389', '27'],
 ['1990', '4071333', '28'],
 ['1990', '4525939', '29'],
 ['1990', '4410195', '30'],
 ['1990', '4297745', '31'],
 ['1990', '4336307', '32'],
 ['1990', '4234431', '33'],
 ['1990', '4303740', '34'],
 ['1990', '4195281', '35'],
 ['1990', '3994187', '36'],
 ['1990', '3951838', '37'],
 ['1990', '3654319', '38'],
 ['1990', '3872229', '39'],
 ['1990', '3724580', '40'],
 ['1990', '3606064', '41'],
 ['1990', '3677304', '42'],
 ['1990', '3626142', '43'],
 ['1990', '2862336', '44'],
 ['1990', '2878765', '45'],
 ['1990', '2862341', '46'],
 ['1990', '2931584', '47'],
 ['1990', '2484431', '48'],
 ['1990', '2562004', '49'],
 ['1990', '2400997', '50'],
 ['1990', '2315471', '51'],
 ['1990', '2244526', '52'],
 ['1990', '2153483', '53'],
 ['1990', '2194629', '54'],
 ['1990', '2158147', '55'],
 ['1990', '2036061', '56'],
 ['1990', '2092153', '57'],
 ['1990', '2008575', '58'],
 ['1990', '2193030', '59'],
 ['1990', '2145541', '60'],
 ['1990', '2104731', '61'],
 ['1990', '2150802', '62'],
 ['1990', '2100082', '63'],
 ['1990', '2125234', '64'],
 ['1990', '2123213', '65'],
 ['1990', '2050096', '66'],
 ['1990', '1999525', '67'],
 ['1990', '1977982', '68'],
 ['1990', '1916276', '69'],
 ['1990', '1759331', '70'],
 ['1990', '1680703', '71'],
 ['1990', '1593732', '72'],
 ['1990', '1499553', '73'],
 ['1990', '1447498', '74'],
 ['1990', '1392544', '75'],
 ['1990', '1291210', '76'],
 ['1990', '1227035', '77'],
 ['1990', '1133687', '78'],
 ['1990', '1059302', '79'],
 ['1990', '943884', '80'],
 ['1990', '860465', '81'],
 ['1990', '784081', '82'],
 ['1990', '696882', '83'],
 ['1990', '624430', '84'],
 ['1990', '550554', '85'],
 ['1990', '463240', '86'],
 ['1990', '394819', '87'],
 ['1990', '324364', '88'],
 ['1990', '302073', '89'],
 ['1990', '222967', '90'],
 ['1990', '175213', '91'],
 ['1990', '142126', '92'],
 ['1990', '115852', '93'],
 ['1990', '91968', '94'],
 ['1990', '67864', '95'],
 ['1990', '50322', '96'],
 ['1990', '37567', '97'],
 ['1990', '25910', '98'],
 ['1990', '21364', '99'],
 ['1990', '35818', '100'],
 ['1991', '250500736', '999'],
 ['1991', '4019288', '0'],
 ['1991', '3911261', '1'],
 ['1991', '3776184', '2'],
 ['1991', '3710047', '3'],
 ['1991', '3700920', '4'],
 ['1991', '3709862', '5'],
 ['1991', '3639140', '6'],
 ['1991', '3599050', '7'],
 ['1991', '3536397', '8'],
 ['1991', '3730671', '9'],
 ['1991', '3736577', '10'],
 ['1991', '3612729', '11'],
 ['1991', '3460058', '12'],
 ['1991', '3445345', '13'],
 ['1991', '3364774', '14'],
 ['1991', '3321334', '15'],
 ['1991', '3359714', '16'],
 ['1991', '3368558', '17'],
 ['1991', '3390056', '18'],
 ['1991', '3777901', '19'],
 ['1991', '3995800', '20'],
 ['1991', '3796717', '21'],
 ['1991', '3622879', '22'],
 ['1991', '3555245', '23'],
 ['1991', '3735346', '24'],
 ['1991', '3829710', '25'],
 ['1991', '4040483', '26'],
 ['1991', '4197313', '27'],
 ['1991', '4045618', '28'],
 ['1991', '4512362', '29'],
 ['1991', '4477636', '30'],
 ['1991', '4350878', '31'],
 ['1991', '4352374', '32'],
 ['1991', '4353875', '33'],
 ['1991', '4408710', '34'],
 ['1991', '4297648', '35'],
 ['1991', '4129509', '36'],
 ['1991', '4049987', '37'],
 ['1991', '3755015', '38'],
 ['1991', '4059064', '39'],
 ['1991', '3771934', '40'],
 ['1991', '3644990', '41'],
 ['1991', '3606668', '42'],
 ['1991', '3646858', '43'],
 ['1991', '3759336', '44'],
 ['1991', '2807497', '45'],
 ['1991', '2805926', '46'],
 ['1991', '2894904', '47'],
 ['1991', '2805774', '48'],
 ['1991', '2718184', '49'],
 ['1991', '2498767', '50'],
 ['1991', '2319022', '51'],
 ['1991', '2311504', '52'],
 ['1991', '2265582', '53'],
 ['1991', '2189645', '54'],
 ['1991', '2138170', '55'],
 ['1991', '2188633', '56'],
 ['1991', '2041514', '57'],
 ['1991', '1959518', '58'],
 ['1991', '2120829', '59'],
 ['1991', '2137646', '60'],
 ['1991', '2097909', '61'],
 ['1991', '2092813', '62'],
 ['1991', '2157453', '63'],
 ['1991', '2125205', '64'],
 ['1991', '2070755', '65'],
 ['1991', '2073343', '66'],
 ['1991', '2020898', '67'],
 ['1991', '1911675', '68'],
 ['1991', '1975541', '69'],
 ['1991', '1863538', '70'],
 ['1991', '1707808', '71'],
 ['1991', '1640755', '72'],
 ['1991', '1511856', '73'],
 ['1991', '1465819', '74'],
 ['1991', '1407170', '75'],
 ['1991', '1331196', '76'],
 ['1991', '1239235', '77'],
 ['1991', '1196545', '78'],
 ['1991', '1072676', '79'],
 ['1991', '966479', '80'],
 ['1991', '881078', '81'],
 ['1991', '799491', '82'],
 ['1991', '734210', '83'],
 ['1991', '635848', '84'],
 ['1991', '541268', '85'],
 ['1991', '499643', '86'],
 ['1991', '416249', '87'],
 ['1991', '351180', '88'],
 ['1991', '285315', '89'],
 ['1991', '261822', '90'],
 ['1991', '190250', '91'],
 ['1991', '147174', '92'],
 ['1991', '117421', '93'],
 ['1991', '93849', '94'],
 ['1991', '72563', '95'],
 ['1991', '52626', '96'],
 ['1991', '38199', '97'],
 ['1991', '27877', '98'],
 ['1991', '18678', '99'],
 ['1991', '38390', '100'],
 ['1992', '254002769', '999'],
 ['1992', '3978783', '0'],
 ['1992', '3991076', '1'],
 ['1992', '3920586', '2'],
 ['1992', '3791155', '3'],
 ['1992', '3774974', '4'],
 ['1992', '3710100', '5'],
 ['1992', '3716081', '6'],
 ['1992', '3663505', '7'],
 ['1992', '3504392', '8'],
 ['1992', '3778671', '9'],
 ['1992', '3771318', '10'],
 ['1992', '3713280', '11'],
 ['1992', '3639516', '12'],
 ['1992', '3511574', '13'],
 ['1992', '3489321', '14'],
 ['1992', '3418746', '15'],
 ['1992', '3359157', '16'],
 ['1992', '3440416', '17'],
 ['1992', '3315838', '18'],
 ['1992', '3547595', '19'],
 ['1992', '3748770', '20'],
 ['1992', '3921799', '21'],
 ['1992', '3730319', '22'],
 ['1992', '3635751', '23'],
 ['1992', '3666070', '24'],
 ['1992', '3759474', '25'],
 ['1992', '3850045', '26'],
 ['1992', '4121600', '27'],
 ['1992', '4055168', '28'],
 ['1992', '4443944', '29'],
 ['1992', '4493758', '30'],
 ['1992', '4408461', '31'],
 ['1992', '4409094', '32'],
 ['1992', '4364890', '33'],
 ['1992', '4522282', '34'],
 ['1992', '4416007', '35'],
 ['1992', '4228105', '36'],
 ['1992', '4178863', '37'],
 ['1992', '3868850', '38'],
 ['1992', '4131846', '39'],
 ['1992', '3980005', '40'],
 ['1992', '3684126', '41'],
 ['1992', '3654144', '42'],
 ['1992', '3581438', '43'],
 ['1992', '3767622', '44'],
 ['1992', '3705664', '45'],
 ['1992', '2737432', '46'],
 ['1992', '2838982', '47'],
 ['1992', '2782099', '48'],
 ['1992', '3045151', '49'],
 ['1992', '2666243', '50'],
 ['1992', '2414219', '51'],
 ['1992', '2318527', '52'],
 ['1992', '2329338', '53'],
 ['1992', '2305876', '54'],
 ['1992', '2137848', '55'],
 ['1992', '2159726', '56'],
 ['1992', '2193357', '57'],
 ['1992', '1925839', '58'],
 ['1992', '2057575', '59'],
 ['1992', '2076812', '60'],
 ['1992', '2086835', '61'],
 ['1992', '2088759', '62'],
 ['1992', '2098580', '63'],
 ['1992', '2179547', '64'],
 ['1992', '2073787', '65'],
 ['1992', '2024844', '66'],
 ['1992', '2047178', '67'],
 ['1992', '1932053', '68'],
 ['1992', '1905327', '69'],
 ['1992', '1924149', '70'],
 ['1992', '1805897', '71'],
 ['1992', '1666965', '72'],
 ['1992', '1563222', '73'],
 ['1992', '1478260', '74'],
 ['1992', '1423969', '75'],
 ['1992', '1344873', '76'],
 ['1992', '1275052', '77'],
 ['1992', '1204358', '78'],
 ['1992', '1131272', '79'],
 ['1992', '985918', '80'],
 ['1992', '898254', '81'],
 ['1992', '820093', '82'],
 ['1992', '745759', '83'],
 ['1992', '670263', '84'],
 ['1992', '554670', '85'],
 ['1992', '490762', '86'],
 ['1992', '448504', '87'],
 ['1992', '370120', '88'],
 ['1992', '308908', '89'],
 ['1992', '246155', '90'],
 ['1992', '222914', '91'],
 ['1992', '159648', '92'],
 ['1992', '121401', '93'],
 ['1992', '94760', '94'],
 ['1992', '73306', '95'],
 ['1992', '56337', '96'],
 ['1992', '39884', '97'],
 ['1992', '28237', '98'],
 ['1992', '19968', '99'],
 ['1992', '38778', '100'],
 ['1993', '257590755', '999'],
 ['1993', '3914106', '0'],
 ['1993', '3959764', '1'],
 ['1993', '4005671', '2'],
 ['1993', '3945023', '3'],
 ['1993', '3864424', '4'],
 ['1993', '3790345', '5'],
 ['1993', '3721222', '6'],
 ['1993', '3749516', '7'],
 ['1993', '3585318', '8'],
 ['1993', '3728262', '9'],
 ['1993', '3831160', '10'],
 ['1993', '3756297', '11'],
 ['1993', '3748653', '12'],
 ['1993', '3693985', '13'],
 ['1993', '3560908', '14'],
 ['1993', '3548788', '15'],
 ['1993', '3460191', '16'],
 ['1993', '3437380', '17'],
 ['1993', '3396686', '18'],
 ['1993', '3453391', '19'],
 ['1993', '3524198', '20'],
 ['1993', '3688924', '21'],
 ['1993', '3861346', '22'],
 ['1993', '3750593', '23'],
 ['1993', '3746766', '24'],
 ['1993', '3705169', '25'],
 ['1993', '3776647', '26'],
 ['1993', '3936926', '27'],
 ['1993', '4004878', '28'],
 ['1993', '4417843', '29'],
 ['1993', '4458748', '30'],
 ['1993', '4421383', '31'],
 ['1993', '4477544', '32'],
 ['1993', '4422418', '33'],
 ['1993', '4528813', '34'],
 ['1993', '4548003', '35'],
 ['1993', '4345668', '36'],
 ['1993', '4274319', '37'],
 ['1993', '4014851', '38'],
 ['1993', '4218629', '39'],
 ['1993', '4077962', '40'],
 ['1993', '3878940', '41'],
 ['1993', '3702022', '42'],
 ['1993', '3631743', '43'],
 ['1993', '3687515', '44'],
 ['1993', '3735882', '45'],
 ['1993', '3614308', '46'],
 ['1993', '2771682', '47'],
 ['1993', '2739110', '48'],
 ['1993', '2999946', '49'],
 ['1993', '3005605', '50'],
 ['1993', '2576514', '51'],
 ['1993', '2417832', '52'],
 ['1993', '2332249', '53'],
 ['1993', '2372285', '54'],
 ['1993', '2256557', '55'],
 ['1993', '2151968', '56'],
 ['1993', '2163794', '57'],
 ['1993', '2084423', '58'],
 ['1993', '2010754', '59'],
 ['1993', '2023266', '60'],
 ['1993', '2023506', '61'],
 ['1993', '2080944', '62'],
 ['1993', '2093494', '63'],
 ['1993', '2116109', '64'],
 ['1993', '2129269', '65'],
 ['1993', '2030380', '66'],
 ['1993', '2002274', '67'],
 ['1993', '1957202', '68'],
 ['1993', '1921069', '69'],
 ['1993', '1859939', '70'],
 ['1993', '1861256', '71'],
 ['1993', '1763625', '72'],
 ['1993', '1596766', '73'],
 ['1993', '1529550', '74'],
 ['1993', '1436064', '75'],
 ['1993', '1361546', '76'],
 ['1993', '1287469', '77'],
 ['1993', '1235979', '78'],
 ['1993', '1139346', '79'],
 ['1993', '1046869', '80'],
 ['1993', '914917', '81'],
 ['1993', '838635', '82'],
 ['1993', '763386', '83'],
 ['1993', '681417', '84'],
 ['1993', '589595', '85'],
 ['1993', '502691', '86'],
 ['1993', '440168', '87'],
 ['1993', '398920', '88'],
 ['1993', '325655', '89'],
 ['1993', '265671', '90'],
 ['1993', '208907', '91'],
 ['1993', '187034', '92'],
 ['1993', '131640', '93'],
 ['1993', '97642', '94'],
 ['1993', '73323', '95'],
 ['1993', '56980', '96'],
 ['1993', '42674', '97'],
 ['1993', '29405', '98'],
 ['1993', '20084', '99'],
 ['1993', '40242', '100'],
 ['1994', '260894994', '999'],
 ['1994', '3858262', '0'],
 ['1994', '3900186', '1'],
 ['1994', '3973204', '2'],
 ['1994', '4034620', '3'],
 ['1994', '4020946', '4'],
 ['1994', '3878296', '5'],
 ['1994', '3799198', '6'],
 ['1994', '3756011', '7'],
 ['1994', '3680540', '8'],
 ['1994', '3789299', '9'],
 ['1994', '3783878', '10'],
 ['1994', '3817232', '11'],
 ['1994', '3792481', '12'],
 ['1994', '3797696', '13'],
 ['1994', '3741572', '14'],
 ['1994', '3617868', '15'],
 ['1994', '3586130', '16'],
 ['1994', '3529345', '17'],
 ['1994', '3403406', '18'],
 ['1994', '3526783', '19'],
 ['1994', '3436150', '20'],
 ['1994', '3471825', '21'],
 ['1994', '3634644', '22'],
 ['1994', '3880906', '23'],
 ['1994', '3855739', '24'],
 ['1994', '3793525', '25'],
 ['1994', '3711596', '26'],
 ['1994', '3858861', '27'],
 ['1994', '3833567', '28'],
 ['1994', '4308332', '29'],
 ['1994', '4446117', '30'],
 ['1994', '4364895', '31'],
 ['1994', '4481756', '32'],
 ['1994', '4474131', '33'],
 ['1994', '4567592', '34'],
 ['1994', '4560164', '35'],
 ['1994', '4465640', '36'],
 ['1994', '4378180', '37'],
 ['1994', '4123123', '38'],
 ['1994', '4330346', '39'],
 ['1994', '4184228', '40'],
 ['1994', '3962668', '41'],
 ['1994', '3902323', '42'],
 ['1994', '3678019', '43'],
 ['1994', '3722260', '44'],
 ['1994', '3673249', '45'],
 ['1994', '3641294', '46'],
 ['1994', '3651557', '47'],
 ['1994', '2683535', '48'],
 ['1994', '2931611', '49'],
 ['1994', '2974881', '50'],
 ['1994', '2903027', '51'],
 ['1994', '2581792', '52'],
 ['1994', '2425838', '53'],
 ['1994', '2375624', '54'],
 ['1994', '2324314', '55'],
 ['1994', '2261693', '56'],
 ['1994', '2153802', '57'],
 ['1994', '2068799', '58'],
 ['1994', '2161676', '59'],
 ['1994', '1985312', '60'],
 ['1994', '1966174', '61'],
 ['1994', '2019378', '62'],
 ['1994', '2083722', '63'],
 ['1994', '2105704', '64'],
 ['1994', '2068997', '65'],
 ['1994', '2087202', '66'],
 ['1994', '2010206', '67'],
 ['1994', '1913178', '68'],
 ['1994', '1940695', '69'],
 ['1994', '1878041', '70'],
 ['1994', '1793779', '71'],
 ['1994', '1815702', '72'],
 ['1994', '1695618', '73'],
 ['1994', '1561001', '74'],
 ['1994', '1482840', '75'],
 ['1994', '1371574', '76'],
 ['1994', '1300236', '77'],
 ['1994', '1242409', '78'],
 ['1994', '1167360', '79'],
 ['1994', '1060057', '80'],
 ['1994', '966810', '81'],
 ['1994', '854031', '82'],
 ['1994', '776762', '83'],
 ['1994', '696619', '84'],
 ['1994', '601925', '85'],
 ['1994', '532567', '86'],
 ['1994', '449164', '87'],
 ['1994', '390231', '88'],
 ['1994', '349862', '89'],
 ['1994', '278060', '90'],
 ['1994', '224048', '91'],
 ['1994', '174125', '92'],
 ['1994', '153460', '93'],
 ['1994', '105052', '94'],
 ['1994', '74432', '95'],
 ['1994', '56710', '96'],
 ['1994', '42804', '97'],
 ['1994', '31174', '98'],
 ['1994', '20609', '99'],
 ['1994', '41132', '100'],
 ['1995', '264111934', '999'],
 ['1995', '3795533', '0'],
 ['1995', '3851042', '1'],
 ['1995', '3913560', '2'],
 ['1995', '4006650', '3'],
 ['1995', '4113417', '4'],
 ['1995', '4034558', '5'],
 ['1995', '3885079', '6'],
 ['1995', '3836164', '7'],
 ['1995', '3698335', '8'],
 ['1995', '3865083', '9'],
 ['1995', '3849451', '10'],
 ['1995', '3771812', '11'],
 ['1995', '3854704', '12'],
 ['1995', '3835856', '13'],
 ['1995', '3843476', '14'],
 ['1995', '3797341', '15'],
 ['1995', '3651439', '16'],
 ['1995', '3647189', '17'],
 ['1995', '3506252', '18'],
 ['1995', '3525625', '19'],
 ['1995', '3512604', '20'],
 ['1995', '3389897', '21'],
 ['1995', '3427448', '22'],
 ['1995', '3657916', '23'],
 ['1995', '3982862', '24'],
 ['1995', '3915573', '25'],
 ['1995', '3793190', '26'],
 ['1995', '3795860', '27'],
 ['1995', '3773179', '28'],
 ['1995', '4084286', '29'],
 ['1995', '4359918', '30'],
 ['1995', '4340739', '31'],
 ['1995', '4425012', '32'],
 ['1995', '4470920', '33'],
 ['1995', '4607551', '34'],
 ['1995', '4611265', '35'],
 ['1995', '4473726', '36'],
 ['1995', '4489415', '37'],
 ['1995', '4243513', '38'],
 ['1995', '4402601', '39'],
 ['1995', '4319928', '40'],
 ['1995', '4055157', '41'],
 ['1995', '3993736', '42'],
 ['1995', '3876487', '43'],
 ['1995', '3754845', '44'],
 ['1995', '3726085', '45'],
 ['1995', '3578219', '46'],
 ['1995', '3679136', '47'],
 ['1995', '3552219', '48'],
 ['1995', '2851835', '49'],
 ['1995', '2922181', '50'],
 ['1995', '2872668', '51'],
 ['1995', '2912798', '52'],
 ['1995', '2584799', '53'],
 ['1995', '2471715', '54'],
 ['1995', '2331633', '55'],
 ['1995', '2320762', '56'],
 ['1995', '2262311', '57'],
 ['1995', '2073439', '58'],
 ['1995', '2133712', '59'],
 ['1995', '2143740', '60'],
 ['1995', '1925918', '61'],
 ['1995', '1964606', '62'],
 ['1995', '2020780', '63'],
 ['1995', '2091935', '64'],
 ['1995', '2061423', '65'],
 ['1995', '2030957', '66'],
 ['1995', '2070721', '67'],
 ['1995', '1921796', '68'],
 ['1995', '1893212', '69'],
 ['1995', '1902081', '70'],
 ['1995', '1808827', '71'],
 ['1995', '1750975', '72'],
 ['1995', '1755526', '73'],
 ['1995', '1659178', '74'],
 ['1995', '1513539', '75'],
 ['1995', '1417718', '76'],
 ['1995', '1310051', '77'],
 ['1995', '1252363', '78'],
 ['1995', '1175042', '79'],
 ['1995', '1095675', '80'],
 ['1995', '977731', '81'],
 ['1995', '905828', '82'],
 ['1995', '789804', '83'],
 ['1995', '710736', '84'],
 ['1995', '620444', '85'],
 ['1995', '544643', '86'],
 ['1995', '476793', '87'],
 ['1995', '399353', '88'],
 ['1995', '343347', '89'],
 ['1995', '298796', '90'],
 ['1995', '234806', '91'],
 ['1995', '187381', '92'],
 ['1995', '143135', '93'],
 ['1995', '122792', '94'],
 ['1995', '79834', '95'],
 ['1995', '57982', '96'],
 ['1995', '42822', '97'],
 ['1995', '31385', '98'],
 ['1995', '21889', '99'],
 ['1995', '42664', '100'],
 ['1996', '267287697', '999'],
 ['1996', '3761856', '0'],
 ['1996', '3795933', '1'],
 ['1996', '3865461', '2'],
 ['1996', '3952344', '3'],
 ['1996', '4087755', '4'],
 ['1996', '4128842', '5'],
 ['1996', '4041199', '6'],
 ['1996', '3926068', '7'],
 ['1996', '3791065', '8'],
 ['1996', '3861041', '9'],
 ['1996', '3932216', '10'],
 ['1996', '3840197', '11'],
 ['1996', '3811906', '12'],
 ['1996', '3894294', '13'],
 ['1996', '3881197', '14'],
 ['1996', '3899051', '15'],
 ['1996', '3829185', '16'],
 ['1996', '3704833', '17'],
 ['1996', '3633208', '18'],
 ['1996', '3622368', '19'],
 ['1996', '3516340', '20'],
 ['1996', '3466635', '21'],
 ['1996', '3353253', '22'],
 ['1996', '3454222', '23'],
 ['1996', '3751470', '24'],
 ['1996', '4058466', '25'],
 ['1996', '3909799', '26'],
 ['1996', '3883993', '27'],
 ['1996', '3728525', '28'],
 ['1996', '3980889', '29'],
 ['1996', '4157684', '30'],
 ['1996', '4246421', '31'],
 ['1996', '4402770', '32'],
 ['1996', '4408629', '33'],
 ['1996', '4592796', '34'],
 ['1996', '4665017', '35'],
 ['1996', '4520656', '36'],
 ['1996', '4487859', '37'],
 ['1996', '4371620', '38'],
 ['1996', '4484127', '39'],
 ['1996', '4416421', '40'],
 ['1996', '4175248', '41'],
 ['1996', '4093391', '42'],
 ['1996', '3967718', '43'],
 ['1996', '3942124', '44'],
 ['1996', '3777009', '45'],
 ['1996', '3628239', '46'],
 ['1996', '3615767', '47'],
 ['1996', '3590613', '48'],
 ['1996', '3741097', '49'],
 ['1996', '2857933', '50'],
 ['1996', '2821122', '51'],
 ['1996', '2885105', '52'],
 ['1996', '2909456', '53'],
 ['1996', '2633954', '54'],
 ['1996', '2429332', '55'],
 ['1996', '2318112', '56'],
 ['1996', '2318983', '57'],
 ['1996', '2192307', '58'],
 ['1996', '2125414', '59'],
 ['1996', '2124438', '60'],
 ['1996', '2075362', '61'],
 ['1996', '1926279', '62'],
 ['1996', '1963538', '63'],
 ['1996', '2024148', '64'],
 ['1996', '2049586', '65'],
 ['1996', '2025435', '66'],
 ['1996', '2017617', '67'],
 ['1996', '1979314', '68'],
 ['1996', '1897639', '69'],
 ['1996', '1859103', '70'],
 ['1996', '1827340', '71'],
 ['1996', '1764408', '72'],
 ['1996', '1700208', '73'],
 ['1996', '1717056', '74'],
 ['1996', '1606282', '75'],
 ['1996', '1446156', '76'],
 ['1996', '1351744', '77'],
 ['1996', '1257254', '78'],
 ['1996', '1183800', '79'],
 ['1996', '1109988', '80'],
 ['1996', '1006892', '81'],
 ['1996', '917096', '82'],
 ['1996', '834340', '83'],
 ['1996', '722029', '84'],
 ['1996', '636784', '85'],
 ['1996', '560430', '86'],
 ['1996', '486561', '87'],
 ['1996', '423360', '88'],
 ['1996', '350906', '89'],
 ['1996', '291704', '90'],
 ['1996', '251345', '91'],
 ['1996', '195809', '92'],
 ['1996', '153594', '93'],
 ['1996', '113751', '94'],
 ['1996', '92358', '95'],
 ['1996', '62198', '96'],
 ['1996', '43605', '97'],
 ['1996', '31226', '98'],
 ['1996', '21811', '99'],
 ['1996', '44668', '100'],
 ['1997', '270567546', '999'],
 ['1997', '3743851', '0'],
 ['1997', '3770958', '1'],
 ['1997', '3813423', '2'],
 ['1997', '3911618', '3'],
 ['1997', '4037247', '4'],
 ['1997', '4106729', '5'],

In [21]:
df_prueba=pd.DataFrame(datos_prueba)
df_prueba

         0          1    2
0     YEAR    TOT_POP  AGE
1     1990  247150736  999
2     1990    3947313    0
3     1990    3769554    1
4     1990    3702679    2
...    ...        ...  ...
1118  2000      72680   96
1119  2000      52844   97
1120  2000      36003   98
1121  2000      27162   99
1122  2000      50454  100

[1123 rows x 3 columns]

In [22]:
df_prueba.columns = df_prueba.iloc[0]

In [23]:
df_prueba.columns

Index(['YEAR', 'TOT_POP', 'AGE'], dtype='object', name=0)

In [26]:
df_prueba["YEAR"].value_counts()

1990    102
1991    102
1992    102
1993    102
1994    102
1995    102
1996    102
1997    102
1998    102
1999    102
2000    102
YEAR      1
Name: YEAR, dtype: int64

In [30]:
prueba_dos = requests.get("https://api.census.gov/data/1980/pep/int_natcivpop?get=YEAR,TOT_POP,AGE&key=2e1b6aa4e6f43e28f2ee12c898c064df825476d0")

In [32]:
prueba_dos.status_code

404

In [ ]:
prueba_dos.status_code

In [ ]:
datos_prueba_dos=prueba_dos.json()
df_prueba_dos=pd.DataFrame(datos_prueba_dos)
df_prueba_dos

In [ ]:
df_prueba_dos.shape

In [ ]:
https://api.census.gov/data/2000/pep/int_housingunits?get=HUEST,GEONAME,DATE_DESC&for=state:*&DATE_=1&key=YOUR_KEY_GOES_HERE

In [ ]:
https://api.census.gov/data/1990/pep/int_natcivpop?get=YEAR,TOT_POP,AGE&key=YOUR_KEY_GOES_HERE

## Es el cociente entre el crecimiento natural anual (nacimientos menos defunciones) de un determinado período y la población media del mismo período.


Por ejemplo, para obtener los 
datos de densidad de población de un estado específico en el año 2019, la URL sería algo así:
    
    
    https://api.census.gov/data/2019/pep/population?get=NAME,DENSITY&for=STATE:XX
    
También puedes acceder a los datos históricos de población y densidad de población para todos los estados de Estados Unidos desde los años 1910 hasta 2019.

https://api.census.gov/data/timeseries/pep/population
El año de los datos que deseas obtener, utilizando el parámetro "time". Por ejemplo, "time=2010" para obtener los datos de 2010.

El nivel geográfico para los datos que deseas obtener, utilizando el parámetro "for". Por ejemplo, "for=STATE:*" para obtener los datos para todos los estados.

Los campos que deseas obtener, utilizando el parámetro "get". Por ejemplo, "get=NAME,POP,DENSITY" para obtener el nombre del estado, la población y la densidad de población

-------------

https://api.census.gov/data/timeseries/pep/population?get=NAME,POP,DENSITY&time=from+1910&for=STATE:*&key=YOUR_API_KEY

https://api.census.gov/data/timeseries/pep/population es la URL base para acceder a los datos históricos de población y densidad de población.
get=NAME,POP,DENSITY especifica los campos que deseas obtener, en este caso el nombre del estado, la población y la densidad de población.
time=from+1910 especifica el rango de tiempo para los datos, en este caso desde el año 1910 hasta la fecha actual.
for=STATE:* especifica el nivel geográfico para los datos, en este caso todos los estados.
key=YOUR_API_KEY especifica tu clave de acceso a la API.


Composición étnica de la población
natalidad, mortalidad migracion 

Para obtener estos datos, debes especificar los campos que deseas obtener en el parámetro "get" en la URL de la API. Por ejemplo, si quieres obtener datos sobre la natalidad, debes incluir el campo "BIRTHS" en el parámetro "get".

https://api.census.gov/data/timeseries/pep/population?get=NAME,BIRTHS&time=from+1910&for=STATE:*&key=YOUR_API_KEY

"NAME" (nombre del estado)
"NAME_WHITE" (población blanca)
"NAME_BLACK" (población negra)
"NAME_AMIN" (población indígena americana)
"NAME_ASIAN" (población asiática)
"NAME_NHOPI" (población nativa hawaiana y de otras islas del Pacífico)
"NAME_OTHER" (población de otra raza)
"NAME_2MORE" (población de dos o más razas)

https://api.census.gov/data/timeseries/pep/population?get=NAME,NAME_WHITE,NAME_BLACK&time=from+1910&for=STATE:*&key=YOUR_API_KEY


https://api.census.gov/data.html
https://iqss.github.io/datafest-project/optional-u-s-census-data-python.html

https://kepler.gl/demo
https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_historical_population



https://www.kaggle.com/code/eames07/gun-incidents-usa-eda-data-visualization



https://en.wikipedia.org/wiki/Historical_racial_and_ethnic_demographics_of_the_United_States


https://www.kaggle.com/code/umeshnarayanappa/map-extinct-endangered-languages-matplotlib

https://www.kaggle.com/code/chanchalkhemani/analysis-of-extinct-and-endangered-languages
https://www.kaggle.com/code/devisangeetha/preserve-languages
https://www.kaggle.com/code/abigaillarion/extinct-languages-in-united-states